NUM_EPOCHS = 30
ALPHA = 5e-3        # learning rate
BATCH_SIZE = 10     # how many episodes we want to pack into an epoch
GAMMA = 0.99        # discount rate
HIDDEN_SIZE = 64    # number of hidden nodes we have in our dnn
BETA = 0.1          # the entropy bonus multiplier
LOG_INTERVAL = 10   # how often we need to 
USE_GPU = True      # whether we use gpu
WORLD_SIZE = 20     #